[tool.poetry]
name = "statistik"
version = "0.1.0"
description = ""
authors = ["kris"]

[tool.poetry.dependencies]
python = "^3.9"
seaborn = "^0.11.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
